// <auto-generated />
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(CopagoContext))]
    partial class CopagoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity.Copago", b =>
                {
                    b.Property<string>("IdentificacionPaciente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Porcentaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalarioTrabajador")
                        .HasColumnType("float");

                    b.Property<double>("ValorServicio")
                        .HasColumnType("float");

                    b.HasKey("IdentificacionPaciente");

                    b.ToTable("Copagos");
                });
#pragma warning restore 612, 618
        }
    }
}
